package in.onenotify.workflow;

public enum WorkflowState {
  DRAFT,
  DOCUMENTS_PENDING,
  READY_TO_SUBMIT,
  USER_APPROVAL_REQUIRED,
  SUBMITTED,
  PROVIDER_ACKNOWLEDGED,
  UNDER_REVIEW,
  ADDITIONAL_DOCUMENTS_REQUIRED,
  RESUBMITTED,
  APPROVED,
  COMPLETED,
  REJECTED,
  ESCALATION_REQUIRED,
  PAUSED,
  CANCELLED,
  FAILED,
  EXTERNAL_ACTION_REQUIRED
}
